# ~/.config/starship.toml
#  â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
# https://gist.github.com/ryo-ARAKI/48a11585299f9032fa4bda60c9bba593
# https://github.com/archaict/Project/blob/master/Dotfiles/.config/starship.toml
#  â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
add_newline = true
command_timeout = 1_000

# format = """
# [â”Œâ”€>](bold #2980b9) \\[$time\\]( [â”€â”€â”€](bold #2980b9) \\[$cmd_duration\\])( [â”€â”€â”€](bold #2980b9) $terraform$golang$nodejs$python$rust)
# [â”‚](bold #2980b9) $character$username$hostname$directory$git_branch$git_commit$git_state$git_status
# [â””â”€>](bold #2980b9) [\\$](bold) """

format = """
[â”Œâ”€â”€ âœ–](bold #fafafa)[ á›ˆáš±á›Ÿá›—á›ˆá› ](bold #fabd2f)[âœ– â”€â”€â”€(bold #2980b9) \\[$time\\]( [â”€â”€â”€](bold #fafafa) \\[$cmd_duration\\])( [â”€â”€â”€](bold #fafafa) $terraform$golang$nodejs$python$rust)â”€â”€â”€â”€â”€â”€â”€â”](bold #fafafa)
[â”‚](bold #fafafa) $character$username$hostname$directory$git_branch$git_commit$git_state$git_status
[â””â”€â”€ ](bold #fafafa)[Î»](bold #64AECC) """

[character]
success_symbol = "[â›¬ ](bold white)[â¯](bold green)"
error_symbol = "[â›¬ ](bold white)[â¯](bold red)"

# [character]
# success_symbol = " (bold #fafafa)[Î»](bold #64AECC) "
# error_symbol   = " [â””â”€â”€ ](bold #fafafa)[Î»](bold #64AECC) "

[line_break]
disabled = false

[username]
show_always = true
format = "[$user]($style) @ "
style_user = "#3498db bold"

[hostname]
ssh_only = true
format = "[$hostname]($style) in (red)"

[directory]
truncation_length = 5
format = "[$read_only]($read_only_style)[$path]($style) "
truncation_symbol = "â€¦/"

[cmd_duration]
min_time = 3_000
format = "took [$duration]($style)"

[golang]
symbol = "ğŸ¹"
version_format = "v${major}.${minor}"
format = '[î‚°](#2980b9 bg:none inverted)[\[go:$symbol|($version)\]]($style)[î‚°](#2980b9 bg:none)'
style = "white bold bg:#2980b9"

[nodejs]
symbol = "â¬¡ "
version_format = "v${major}.${minor}"
format = '[î‚°](#f1c40f bg:none inverted)[\[js:$symbol|($version)\]]($style)[î‚°](#f1c40f bg:none)'
style = "black bold bg:#f1c40f"

[python]
symbol = "ğŸ"
version_format = "v${major}.${minor}"
format = '[î‚°](#16a085 bg:none inverted)[\[py:${symbol}${pyenv_prefix}|(${version})(\($virtualenv\))\]]($style)[î‚°](#16a085 bg:none)'
style = "white bold bg:#16a085"

[rust]
symbol = "ğŸ¦€"
version_format = "v${major}.${minor}"
format = '[î‚°](#e74c3c bg:none inverted)[\[rs:$symbol|($version)\]]($style)[î‚°](#e74c3c bg:none)'
style = "white bold bg:#e74c3c"

[kubernetes]
disabled = false

[terraform]
format = "[$symbol$workspace]($style) "

[git_branch]

[git_commit]
style = "bold yellow"

[git_state]

[git_status]

[gcloud]

[time]
disabled = false
format = "[$time]($style)"

